.github/workflows/test.yml

Fix CI runners

---

mart/attack/callbacks/visualizer.py
tests/conftest.py
tests/test_visualizer.py

Added test case for the `PerturbedImageVisualizer` class.
Fixes #14

Add tests for PerturbedImageVisualizer class

---

tests/helpers/run_sh_command.py

The fix makes it easier to debug failed tests with stdout.

Return stdout for debugging failed tests

---

.github/workflows/test.yml
pyproject.toml

The current CI workflow installs some dependency for the development purpose, but we should reuse the optional dependency defined in `pyproject.toml`.

Automatically installing optional dependency in CI

---

mart/attack/objective/classification.py

Fix a Callable type annotation.

---

.github/workflows/test.yml
README.md

Since we exclusively use Python 3.9, we would only test with Python 3.9.

Remove Python 3.10 from test workflow.

---

pyproject.toml

Upgrade to PyTorch 1.13.1.

---

mart/attack/adversary_wrapper.py
mart/configs/attack/classification_autoattack.yaml
mart/utils/adapters.py
tests/test_experiments.py

Fixes #79
Test run on GPU, attacking a pretrained model. 
```bash
python -m mart \
experiment=CIFAR10_RobustBench \
fit=false \
+attack@model.modules.input_adv_test=classification_autoattack \
trainer=ddp +trainer.limit_test_batches=1
```

Fix the autoattack wrapper

---

mart/attack/adversary.py
mart/configs/experiment/CIFAR10_CNN_Adv.yaml
mart/configs/experiment/COCO_TorchvisionFasterRCNN_Adv.yaml
mart/configs/model/classifier.yaml
mart/configs/model/torchvision_retinanet.yaml
tests/test_adversary.py

`mart.adversary.NoAdversary` is unnecessary given #55. This PR removes `NoAdversary` and fixes any associated issues.

Remove `NoAdversary`

---

mart/attack/composer.py
mart/configs/attack/composer/mask_additive.yaml
tests/test_composer.py

This PR adds `MaskAdditve` as a new `Composer`.

Add `MaskAdditive` composer.

---

mart/configs/optimizer/sgd.yaml
mart/models/modular.py

Simplify optimizer configs by hiding `OptimizerFactory` in `LitModular` (and `Adversary`)

---

mart/attack/adversary.py
mart/callbacks/progress_bar.py
mart/configs/attack/classification_eps1.75_fgsm.yaml
mart/configs/callbacks/progress_bar.yaml

- Log `gain` as a metric on progress bar, so that LR scheduler also sees it. 
- Remove the renaming mechanism `loss`->`gain`.
- (Our outdated PL displays `loss` in running mean and the raw `gain`, but newer PL will hide `loss`.)
- Change to a more natural config name: `disable` -> `enable`.

Improve Adversary's progress bar

---

mart/attack/initializer.py
mart/configs/attack/perturber/initializer/image.yaml

This PR adds the ability to initialize a perturbation using an existing image.

Add Image initializer

---

tests/conftest.py
tests/test_experiments.py

We have to remove these tests because CI always fails them.

Purge tests on RobustBench

---

mart/attack/__init__.py
pyproject.toml

Move ART dependency to extras.

Move ART to extras

---

mart/attack/composer.py
mart/configs/attack/adversary.yaml
mart/configs/attack/classification_fgsm_linf.yaml
mart/configs/attack/classification_pgd_linf.yaml
mart/configs/attack/composer/additive.yaml
mart/configs/attack/composer/default.yaml
mart/configs/attack/composer/functions/additive.yaml
mart/configs/attack/composer/functions/mask.yaml
mart/configs/attack/composer/functions/overlay.yaml
mart/configs/attack/composer/mask_additive.yaml
mart/configs/attack/composer/overlay.yaml
mart/configs/attack/object_detection_mask_adversary.yaml
mart/configs/attack/object_detection_mask_adversary_missed.yaml
tests/test_adversary.py
tests/test_composer.py

This PR adds `functions` to `Composer` so that we can compose a `Composer` with a sequence of `Functions`. One use case is that we can reuse the `Mask` and `Additive` functions to compose a `MaskAdditive` Composer.
* Add the `mart.attack.composer.Function` base class and three children classes `Additive`, `Mask` and `Overlay`.
* Add `Composer(functions:dict)` so it is configurable in Hydra.
* Add `Function(order:int)` so we can sort the sequence of `Function`s in `Composer`.
* Update existing configs.
* Update tests.

Add composable functions to Composer

---

pyproject.toml

This PR adds `python-fire` in dependency, which was missing in 
* #224

Add python-fire in MART's dependency.

---

pyproject.toml

This PR updates dependency on PyTorch to >=2.0.1 for better compatibility.

Update dependency on PyTorch >=2.0.1

---

mart/attack/composer.py
mart/configs/attack/adversary.yaml
mart/configs/attack/classification_fgsm_linf.yaml
mart/configs/attack/classification_pgd_linf.yaml
mart/configs/attack/composer/additive.yaml
mart/configs/attack/composer/default.yaml
mart/configs/attack/composer/mask_additive.yaml
mart/configs/attack/composer/modules/additive.yaml
mart/configs/attack/composer/modules/mask.yaml
mart/configs/attack/composer/modules/overlay.yaml
mart/configs/attack/composer/overlay.yaml
mart/configs/attack/object_detection_mask_adversary.yaml
mart/configs/attack/object_detection_mask_adversary_missed.yaml
tests/test_adversary.py
tests/test_composer.py

This PR implements a modular `Composer` which reuses `SequentialDict` in `LitModular`.
The modular `Composer` makes it easier to define complex composition in a modular manner.

Modular Composer

---

.github/workflows/code-quality-main.yaml
.github/workflows/code-quality-pr.yaml
.github/workflows/test.yml

This PR makes workflows follow the principle of least privilege by specifying top level permission `read-all` for all workflows.

Specify read-all permissions in workflows.

---

.pre-commit-config.yaml

This PR should fix the code quality check in main. Example: https://github.com/IntelLabs/MART/actions/runs/14780650313/job/41498642433

Upgrade pre-commit mdformat 0.7.14->0.7.22
